# Generated by Django 5.1.5 on 2025-02-05 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_users_user_posts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover_img')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.posts')),
            ],
        ),
    ]
