# Generated by Django 5.1.5 on 2025-02-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_img'),
        ),
        migrations.DeleteModel(
            name='Cover',
        ),
    ]
